// src/config/themes.ts
export const themes = {
  NoParkFeeFlow: {
      mainScreen: {
          backgroundImage: '/src/assets/backgrounds/background.jpg',
          textColor: 'text-red-700',
          buttonColor: 'bg-green-500',
          subtitleColor: 'text-red-700',
          title: 'ROSE & CROWN',
          subtitle: 'HOTEL - BAR - RESTAURANT DINING',
      },
      tapToStartScreen: {
          logo: '/src/assets/logos/NoParkFeeFlow/logo.jpg',
          Macmillanlogo: '/src/assets/logos/NoParkFeeFlow/macmillan-logo.png',
          backgroundColor: 'bg-red-500',
          title: 'THIS CAR PARK IS RAISING FUNDS FOR:',
          subtitle: 'Macmillan Cancer Support',
          buttonTextColor: 'text-white',
          buttonColor: 'bg-red-600',
          validateParkingTextColor: 'text-red-600',
          recentLeadersBackgroundColor: 'bg-gray-200',
          poweredByBackgroundColor: 'bg-gray-200',
          recentLeaders: [
              { name: 'DAVE', amount: '£20.00' },
              { name: 'MILLY', amount: '£10.00' },
              { name: 'JEFF', amount: '£2.00' },
          ],
      },
      enterStayDurationScreen: {
          title: 'TELL US HOW LONG YOU\'RE STAYING',
          titleColor: 'text-red-700',
          subtitle: 'Choose how long you want to use the car park and select from below',
          buttonColor: 'bg-amber-500',
          buttonTextColor: 'bg-amber-500',
          moreButtonColor: 'bg-green-600',
          moreButtonTextColor: 'text-white',
          buttonBorderColor: 'border-amber-500',
      },
      enterRegNumberScreen: {
          title: 'ENTER YOUR FULL VEHICLE REGISTRATION NUMBER',
          subtitle: 'You must ensure that your full vehicle registration number is entered correctly before pressing continue',
          inputBackgroundColor: 'bg-yellow-400',
          inputTextColor: 'text-gray-900',
          buttonTextColor: 'text-white',
          buttonContinueColor: 'bg-green-700',
          buttonBackColor: 'bg-red-600',
          textColor: 'text-green-900',
          goBackButotntextColor: 'text-red-600',
          inputBorderColor: 'border-red-400',
          inputPlaceholderColor: 'placeholder-red-500',
          buttonHoverColor: 'hover:bg-green-900',
          backButtonHoverColor: 'hover:bg-gray-200'
      },
      checkDetailsScreen: {
          title: 'CHECK YOUR DETAILS BEFORE YOU GO',
          subtitle: 'Please check your details are correct before you continue. You have entered:',
          textColor: 'text-gray-800',
          inputBackgroundColor: 'bg-yellow-400',
          inputDaysBackgroundColor: 'bg-orange-400',
          buttonContinueColor: 'bg-green-700',
          buttonHoverColor: 'hover:bg-green-900',
          backButtonHoverColor: 'hover:bg-gray-200',
          buttonTextColor: 'text-white',
          inputTextColor: 'text-gray-900',
          inputBorderColor: 'border-gray-400',
          inputPlaceholder: 'Enter Registration Number',
          paymentText: 'PAY USING THE CARD READER',
          paymentTextColor: 'text-blue-800',
          arrowIcon: '/src/assets/icons/right-arrow.png',
          nfcIcon: '/src/assets/icons/nfc.png',
          buttonBackText: 'GO BACK & EDIT DETAILS',
          buttonBackBorderColor: 'border-red-600',
          buttonBackTextColor: 'text-red-600',
          buttonBackHoverColor: 'hover:bg-gray-400',
      },
      decisionScreen: {
          textColor: 'text-gray-800',
          inputBackgroundColor: 'bg-yellow-500',
          inputTextColor: 'text-gray-900',
          receiptTextColor: 'text-gray-600',
          inputBorderColor: 'border-gray-400',
          buttonContinueColor: 'bg-green-700',
          buttonHoverColor: 'hover:bg-green-900',
          buttonTextColor: 'text-white',
          subtitleColor: 'text-gray-600',
          qrTextColor: 'text-gray-800',
      }
  },
  MandatoryDonationFlow: {
    mainScreen: {
        backgroundImage: '/src/assets/backgrounds/background.jpg',
        textColor: 'text-red-700',
        buttonColor: 'bg-green-500',
        subtitleColor: 'text-red-700',
        title: 'ROSE & CROWN',
        subtitle: 'HOTEL - BAR - RESTAURANT DINING',
    },
    tapToStartScreen: {
        logo: '/src/assets/logos/NoParkFeeFlow/logo.jpg',
        Macmillanlogo: '/src/assets/logos/NoParkFeeFlow/macmillan-logo.png',
        backgroundColor: 'bg-red-500',
        title: 'THIS CAR PARK IS RAISING FUNDS FOR:',
        subtitle: 'Macmillan Cancer Support',
        buttonTextColor: 'text-white',
        buttonColor: 'bg-red-600',
        validateParkingTextColor: 'text-red-600',
        recentLeadersBackgroundColor: 'bg-gray-200',
        poweredByBackgroundColor: 'bg-gray-200',
        recentLeaders: [
            { name: 'DAVE', amount: '£20.00' },
            { name: 'MILLY', amount: '£10.00' },
            { name: 'JEFF', amount: '£2.00' },
        ],
    },
    enterStayDurationScreen: {
        title: 'TELL US HOW LONG YOU\'RE STAYING',
        titleColor: 'text-red-700',
        subtitle: 'Choose how long you want to use the car park and select from below',
        buttonColor: 'bg-amber-500',
        buttonTextColor: 'bg-amber-500',
        moreButtonColor: 'bg-green-600',
        moreButtonTextColor: 'text-white',
        buttonBorderColor: 'border-amber-500',
    },
    enterRegNumberScreen: {
        title: 'ENTER YOUR FULL VEHICLE REGISTRATION NUMBER',
        subtitle: 'You must ensure that your full vehicle registration number is entered correctly before pressing continue',
        inputBackgroundColor: 'bg-yellow-400',
        inputTextColor: 'text-gray-900',
        buttonTextColor: 'text-white',
        buttonContinueColor: 'bg-green-700',
        buttonBackColor: 'bg-red-600',
        textColor: 'text-green-900',
        goBackButotntextColor: 'text-red-600',
        inputBorderColor: 'border-red-400',
        inputPlaceholderColor: 'placeholder-red-500',
        buttonHoverColor: 'hover:bg-green-900',
        backButtonHoverColor: 'hover:bg-gray-200'
    },
    checkDetailsScreen: {
        title: 'CHECK YOUR DETAILS BEFORE YOU GO',
        subtitle: 'Please check your details are correct before you continue. You have entered:',
        textColor: 'text-gray-800',
        inputBackgroundColor: 'bg-yellow-400',
        inputDaysBackgroundColor: 'bg-orange-400',
        buttonContinueColor: 'bg-green-700',
        buttonHoverColor: 'hover:bg-green-900',
        backButtonHoverColor: 'hover:bg-gray-200',
        buttonTextColor: 'text-white',
        inputTextColor: 'text-gray-900',
        inputBorderColor: 'border-gray-400',
        inputPlaceholder: 'Enter Registration Number',
        paymentText: 'PAY USING THE CARD READER',
        paymentTextColor: 'text-blue-800',
        arrowIcon: '/src/assets/icons/right-arrow.png',
        nfcIcon: '/src/assets/icons/nfc.png',
        buttonBackText: 'GO BACK & EDIT DETAILS',
        buttonBackBorderColor: 'border-red-600',
        buttonBackTextColor: 'text-red-600',
        buttonBackHoverColor: 'hover:bg-gray-400',
    },
    decisionScreen: {
        textColor: 'text-gray-800',
        inputBackgroundColor: 'bg-gray-100',
        inputTextColor: 'text-gray-900',
        receiptTextColor: 'text-gray-300',
        inputBorderColor: 'border-gray-400',
        buttonContinueColor: 'bg-green-700',
        buttonHoverColor: 'hover:bg-green-900',
        buttonTextColor: 'text-white',
        subtitleColor: 'text-gray-600',
        qrTextColor: 'text-gray-800',
    }
},
  // Add more flows and screens as needed
};
