name: Build and deploy Node.js app to Azure Web App - parkingticketingwebapp

on:
  push:
    branches:
      - dynamicsAlioIP
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Build the app
        run: npm run build
        working-directory: ./

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0CB029E3FCBA4210BE340BB3AAA04D34 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F6AC1CCBA1194A6DBF56D3AA7D364D13 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_28A7EFC0DCBA4FA58A44077DF9B0552F }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'parkingticketingwebapp'
          slot-name: 'Production'
          package: .
